### ISSUE TITLE
Entering portal causes a crash.

### ISSUE THREAD

**Issue by BugmanBugman** [TheRandomLabs/Vertical-End-Portals#33]
`---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2020-07-25 22:31:51 CDT
Description: Exception in server tick loop

java.lang.NullPointerException
    at com.therandomlabs.randomportals.handler.NetherPortalTeleportHandler.handle(NetherPortalTeleportHandler.java:176)
    at com.therandomlabs.randomportals.handler.NetherPortalTeleportHandler.onServerTick(NetherPortalTeleportHandler.java:129)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3071_NetherPortalTeleportHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:823)`

**Comment by BugmanBugman** [comment]
This may have to do with the latest update, although i'm not sure

**Comment by TheRandomLabs** [comment]
Yeah, I made an oversight with the latest update. Thanks for reporting!
